tosca_definitions_version: cloudify_dsl_1_3

node_templates:

  aws_node_sanity_application:
    # This node is a test application.
    # The nginx application is defined in scripts/kubernetes/resources is the same as located here: https://github.com/kubernetes/kubernetes/tree/v1.2.0/docs/user-guide/walkthrough
    # The service is started via the API. The API returns the IP and Port of the service.
    # The test_running.py script checks to see if 200 is returned from the IP/Port.
    type: cloudify.nodes.Root
    interfaces:
      cloudify.interfaces.lifecycle:
        create:
          implementation: scripts/kubernetes/test_api.py
          executor: central_deployment_agent
        start:
          implementation: scripts/kubernetes/test_running.py
    relationships:
      - type: cloudify.relationships.contained_in
        target: kubernetes_master_vm
      - type: cloudify.relationships.depends_on
        target: kubernetes_node
